# Generated by Django 5.1.6 on 2025-05-16 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ImageTypeName', models.CharField(max_length=200, null=True)),
                ('ImageTypeDate', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ImageName', models.CharField(max_length=200, null=True)),
                ('ImageURL', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('ImageLink', models.CharField(max_length=200, null=True)),
                ('Active', models.CharField(max_length=200, null=True)),
                ('ImageDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('ImageTypeID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.imagetype')),
            ],
        ),
    ]
