# Generated by Django 5.1.6 on 2025-05-31 17:45

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_imagetype_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MenuNameKH', models.CharField(max_length=200, null=True)),
                ('MenuNameEN', models.CharField(max_length=200, null=True)),
                ('OrderBy', models.IntegerField(blank=True, null=True)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('MenuDetailDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('MenuID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.menu')),
            ],
        ),
    ]
